/* 
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Flowaccount.OpenAPITools.Client.OpenAPIDateConverter;

namespace Flowaccount.OpenAPITools.Model
{
    /// <summary>
    /// ExpenseInlineDocument
    /// </summary>
    [DataContract]
    public partial class ExpenseInlineDocument :  IEquatable<ExpenseInlineDocument>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExpenseInlineDocument" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExpenseInlineDocument() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExpenseInlineDocument" /> class.
        /// </summary>
        /// <param name="documentSerial">เลขที่เอกสาร.</param>
        /// <param name="contactCode">รหัส ผู้ติดต่อ/ผู้จำหน่าย.</param>
        /// <param name="contactName">ชื่อบริษัท (required).</param>
        /// <param name="contactAddress">ที่อยู่ ผู้ติดต่อ/ผู้จำหน่าย.</param>
        /// <param name="contactTaxId">เลขประจำตัวผู้เสียภาษี ผู้ติดต่อ/ผู้จำหน่าย.</param>
        /// <param name="contactBranch">สำนักงาน/สาขา.</param>
        /// <param name="contactPerson">ชื่อผู้ติดต่อ.</param>
        /// <param name="contactEmail">อีเมลผู้ติดต่อ.</param>
        /// <param name="contactNumber">เบอร์มือถือผู้ติดต่อ.</param>
        /// <param name="contactZipCode">รหัสไปรษณีย์ผู้ติดต่อ.</param>
        /// <param name="publishedOn">วันที่เอกสาร รูปแบบ yyyy-MM-dd (required).</param>
        /// <param name="creditType">รูปแบบเครดิต: 1 &#x3D; เครดิต (วัน) / 5 &#x3D; เครดิต (ไม่แสดงวันที่ครบกำหนด) (default to 1).</param>
        /// <param name="creditDays">จำนวนวันที่ให้เครดิต (default to 0).</param>
        /// <param name="dueDate">วันครบกำหนดเอกสาร รูปแบบ yyyy-MM-dd.</param>
        /// <param name="salesName">พนักงานขาย.</param>
        /// <param name="projectName">ชื่อโปรเจค.</param>
        /// <param name="reference">เลขที่อ้างอิง.</param>
        /// <param name="isVatInclusive">มูลค่าเอกสารรวมภาษีแล้วหรือไม่ (default to false).</param>
        /// <param name="discountType">รูปแบบส่วนลดสินค้าแต่ละรายการ: 1 &#x3D; รูปแบบเปอร์เซ็นต์ (%) / 3 &#x3D; รูปแบบจำนวนเงิน (฿) (default to 1).</param>
        /// <param name="items">items.</param>
        /// <param name="subTotal">รวมยอดขาย (required).</param>
        /// <param name="discountAmount">ส่วนลดรวม (default to 0M).</param>
        /// <param name="totalAfterDiscount">ยอดขายหลังหักส่วนลดรวม (required).</param>
        /// <param name="exemptAmount">ยอดขายที่ยกเว้นภาษีมูลค่าเพิ่ม (default to 0M).</param>
        /// <param name="vatableAmount">ยอดขายที่คิดภาษีมูลค่าเพิ่ม (default to 0M).</param>
        /// <param name="vatAmount">ภาษีมูลค่าเพิ่ม (default to 0M).</param>
        /// <param name="grandTotal">รวมทั้งสิ้น (required).</param>
        /// <param name="remarks">หมายเหตุ.</param>
        /// <param name="internalNotes">โน๊ตภายในบริษัท.</param>
        public ExpenseInlineDocument(string documentSerial = default(string), string contactCode = default(string), string contactName = default(string), string contactAddress = default(string), string contactTaxId = default(string), string contactBranch = default(string), string contactPerson = default(string), string contactEmail = default(string), string contactNumber = default(string), string contactZipCode = default(string), DateTime publishedOn = default(DateTime), int creditType = 1, int creditDays = 0, DateTime dueDate = default(DateTime), string salesName = default(string), string projectName = default(string), string reference = default(string), bool isVatInclusive = false, int discountType = 1, List<ExpenseInlineProductItem> items = default(List<ExpenseInlineProductItem>), decimal subTotal = default(decimal), decimal discountAmount = 0M, decimal totalAfterDiscount = default(decimal), decimal exemptAmount = 0M, decimal vatableAmount = 0M, decimal vatAmount = 0M, decimal grandTotal = default(decimal), string remarks = default(string), string internalNotes = default(string))
        {
            // to ensure "contactName" is required (not null)
            if (contactName == null)
            {
                throw new InvalidDataException("contactName is a required property for ExpenseInlineDocument and cannot be null");
            }
            else
            {
                this.ContactName = contactName;
            }
            
            // to ensure "publishedOn" is required (not null)
            if (publishedOn == null)
            {
                throw new InvalidDataException("publishedOn is a required property for ExpenseInlineDocument and cannot be null");
            }
            else
            {
                this.PublishedOn = publishedOn;
            }
            
            // to ensure "subTotal" is required (not null)
            if (subTotal == null)
            {
                throw new InvalidDataException("subTotal is a required property for ExpenseInlineDocument and cannot be null");
            }
            else
            {
                this.SubTotal = subTotal;
            }
            
            // to ensure "totalAfterDiscount" is required (not null)
            if (totalAfterDiscount == null)
            {
                throw new InvalidDataException("totalAfterDiscount is a required property for ExpenseInlineDocument and cannot be null");
            }
            else
            {
                this.TotalAfterDiscount = totalAfterDiscount;
            }
            
            // to ensure "grandTotal" is required (not null)
            if (grandTotal == null)
            {
                throw new InvalidDataException("grandTotal is a required property for ExpenseInlineDocument and cannot be null");
            }
            else
            {
                this.GrandTotal = grandTotal;
            }
            
            this.DocumentSerial = documentSerial;
            this.ContactCode = contactCode;
            this.ContactAddress = contactAddress;
            this.ContactTaxId = contactTaxId;
            this.ContactBranch = contactBranch;
            this.ContactPerson = contactPerson;
            this.ContactEmail = contactEmail;
            this.ContactNumber = contactNumber;
            this.ContactZipCode = contactZipCode;
            // use default value if no "creditType" provided
            if (creditType == null)
            {
                this.CreditType = 1;
            }
            else
            {
                this.CreditType = creditType;
            }
            // use default value if no "creditDays" provided
            if (creditDays == null)
            {
                this.CreditDays = 0;
            }
            else
            {
                this.CreditDays = creditDays;
            }
            this.DueDate = dueDate;
            this.SalesName = salesName;
            this.ProjectName = projectName;
            this.Reference = reference;
            // use default value if no "isVatInclusive" provided
            if (isVatInclusive == null)
            {
                this.IsVatInclusive = false;
            }
            else
            {
                this.IsVatInclusive = isVatInclusive;
            }
            // use default value if no "discountType" provided
            if (discountType == null)
            {
                this.DiscountType = 1;
            }
            else
            {
                this.DiscountType = discountType;
            }
            this.Items = items;
            // use default value if no "discountAmount" provided
            if (discountAmount == null)
            {
                this.DiscountAmount = 0M;
            }
            else
            {
                this.DiscountAmount = discountAmount;
            }
            // use default value if no "exemptAmount" provided
            if (exemptAmount == null)
            {
                this.ExemptAmount = 0M;
            }
            else
            {
                this.ExemptAmount = exemptAmount;
            }
            // use default value if no "vatableAmount" provided
            if (vatableAmount == null)
            {
                this.VatableAmount = 0M;
            }
            else
            {
                this.VatableAmount = vatableAmount;
            }
            // use default value if no "vatAmount" provided
            if (vatAmount == null)
            {
                this.VatAmount = 0M;
            }
            else
            {
                this.VatAmount = vatAmount;
            }
            this.Remarks = remarks;
            this.InternalNotes = internalNotes;
        }
        
        /// <summary>
        /// เลขที่เอกสาร
        /// </summary>
        /// <value>เลขที่เอกสาร</value>
        [DataMember(Name="documentSerial", EmitDefaultValue=true)]
        public string DocumentSerial { get; set; }

        /// <summary>
        /// รหัส ผู้ติดต่อ/ผู้จำหน่าย
        /// </summary>
        /// <value>รหัส ผู้ติดต่อ/ผู้จำหน่าย</value>
        [DataMember(Name="contactCode", EmitDefaultValue=true)]
        public string ContactCode { get; set; }

        /// <summary>
        /// ชื่อบริษัท
        /// </summary>
        /// <value>ชื่อบริษัท</value>
        [DataMember(Name="contactName", EmitDefaultValue=true)]
        public string ContactName { get; set; }

        /// <summary>
        /// ที่อยู่ ผู้ติดต่อ/ผู้จำหน่าย
        /// </summary>
        /// <value>ที่อยู่ ผู้ติดต่อ/ผู้จำหน่าย</value>
        [DataMember(Name="contactAddress", EmitDefaultValue=true)]
        public string ContactAddress { get; set; }

        /// <summary>
        /// เลขประจำตัวผู้เสียภาษี ผู้ติดต่อ/ผู้จำหน่าย
        /// </summary>
        /// <value>เลขประจำตัวผู้เสียภาษี ผู้ติดต่อ/ผู้จำหน่าย</value>
        [DataMember(Name="contactTaxId", EmitDefaultValue=true)]
        public string ContactTaxId { get; set; }

        /// <summary>
        /// สำนักงาน/สาขา
        /// </summary>
        /// <value>สำนักงาน/สาขา</value>
        [DataMember(Name="contactBranch", EmitDefaultValue=true)]
        public string ContactBranch { get; set; }

        /// <summary>
        /// ชื่อผู้ติดต่อ
        /// </summary>
        /// <value>ชื่อผู้ติดต่อ</value>
        [DataMember(Name="contactPerson", EmitDefaultValue=true)]
        public string ContactPerson { get; set; }

        /// <summary>
        /// อีเมลผู้ติดต่อ
        /// </summary>
        /// <value>อีเมลผู้ติดต่อ</value>
        [DataMember(Name="contactEmail", EmitDefaultValue=true)]
        public string ContactEmail { get; set; }

        /// <summary>
        /// เบอร์มือถือผู้ติดต่อ
        /// </summary>
        /// <value>เบอร์มือถือผู้ติดต่อ</value>
        [DataMember(Name="contactNumber", EmitDefaultValue=true)]
        public string ContactNumber { get; set; }

        /// <summary>
        /// รหัสไปรษณีย์ผู้ติดต่อ
        /// </summary>
        /// <value>รหัสไปรษณีย์ผู้ติดต่อ</value>
        [DataMember(Name="contactZipCode", EmitDefaultValue=true)]
        public string ContactZipCode { get; set; }

        /// <summary>
        /// วันที่เอกสาร รูปแบบ yyyy-MM-dd
        /// </summary>
        /// <value>วันที่เอกสาร รูปแบบ yyyy-MM-dd</value>
        [DataMember(Name="publishedOn", EmitDefaultValue=true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime PublishedOn { get; set; }

        /// <summary>
        /// รูปแบบเครดิต: 1 &#x3D; เครดิต (วัน) / 5 &#x3D; เครดิต (ไม่แสดงวันที่ครบกำหนด)
        /// </summary>
        /// <value>รูปแบบเครดิต: 1 &#x3D; เครดิต (วัน) / 5 &#x3D; เครดิต (ไม่แสดงวันที่ครบกำหนด)</value>
        [DataMember(Name="creditType", EmitDefaultValue=true)]
        public int CreditType { get; set; }

        /// <summary>
        /// จำนวนวันที่ให้เครดิต
        /// </summary>
        /// <value>จำนวนวันที่ให้เครดิต</value>
        [DataMember(Name="creditDays", EmitDefaultValue=true)]
        public int CreditDays { get; set; }

        /// <summary>
        /// วันครบกำหนดเอกสาร รูปแบบ yyyy-MM-dd
        /// </summary>
        /// <value>วันครบกำหนดเอกสาร รูปแบบ yyyy-MM-dd</value>
        [DataMember(Name="dueDate", EmitDefaultValue=true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime DueDate { get; set; }

        /// <summary>
        /// พนักงานขาย
        /// </summary>
        /// <value>พนักงานขาย</value>
        [DataMember(Name="salesName", EmitDefaultValue=true)]
        public string SalesName { get; set; }

        /// <summary>
        /// ชื่อโปรเจค
        /// </summary>
        /// <value>ชื่อโปรเจค</value>
        [DataMember(Name="projectName", EmitDefaultValue=true)]
        public string ProjectName { get; set; }

        /// <summary>
        /// เลขที่อ้างอิง
        /// </summary>
        /// <value>เลขที่อ้างอิง</value>
        [DataMember(Name="reference", EmitDefaultValue=true)]
        public string Reference { get; set; }

        /// <summary>
        /// มูลค่าเอกสารรวมภาษีแล้วหรือไม่
        /// </summary>
        /// <value>มูลค่าเอกสารรวมภาษีแล้วหรือไม่</value>
        [DataMember(Name="isVatInclusive", EmitDefaultValue=true)]
        public bool IsVatInclusive { get; set; }

        /// <summary>
        /// รูปแบบส่วนลดสินค้าแต่ละรายการ: 1 &#x3D; รูปแบบเปอร์เซ็นต์ (%) / 3 &#x3D; รูปแบบจำนวนเงิน (฿)
        /// </summary>
        /// <value>รูปแบบส่วนลดสินค้าแต่ละรายการ: 1 &#x3D; รูปแบบเปอร์เซ็นต์ (%) / 3 &#x3D; รูปแบบจำนวนเงิน (฿)</value>
        [DataMember(Name="discountType", EmitDefaultValue=true)]
        public int DiscountType { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name="items", EmitDefaultValue=true)]
        public List<ExpenseInlineProductItem> Items { get; set; }

        /// <summary>
        /// รวมยอดขาย
        /// </summary>
        /// <value>รวมยอดขาย</value>
        [DataMember(Name="subTotal", EmitDefaultValue=true)]
        public decimal SubTotal { get; set; }

        /// <summary>
        /// ส่วนลดรวม
        /// </summary>
        /// <value>ส่วนลดรวม</value>
        [DataMember(Name="discountAmount", EmitDefaultValue=true)]
        public decimal DiscountAmount { get; set; }

        /// <summary>
        /// ยอดขายหลังหักส่วนลดรวม
        /// </summary>
        /// <value>ยอดขายหลังหักส่วนลดรวม</value>
        [DataMember(Name="totalAfterDiscount", EmitDefaultValue=true)]
        public decimal TotalAfterDiscount { get; set; }

        /// <summary>
        /// ยอดขายที่ยกเว้นภาษีมูลค่าเพิ่ม
        /// </summary>
        /// <value>ยอดขายที่ยกเว้นภาษีมูลค่าเพิ่ม</value>
        [DataMember(Name="exemptAmount", EmitDefaultValue=true)]
        public decimal ExemptAmount { get; set; }

        /// <summary>
        /// ยอดขายที่คิดภาษีมูลค่าเพิ่ม
        /// </summary>
        /// <value>ยอดขายที่คิดภาษีมูลค่าเพิ่ม</value>
        [DataMember(Name="vatableAmount", EmitDefaultValue=true)]
        public decimal VatableAmount { get; set; }

        /// <summary>
        /// ภาษีมูลค่าเพิ่ม
        /// </summary>
        /// <value>ภาษีมูลค่าเพิ่ม</value>
        [DataMember(Name="vatAmount", EmitDefaultValue=true)]
        public decimal VatAmount { get; set; }

        /// <summary>
        /// รวมทั้งสิ้น
        /// </summary>
        /// <value>รวมทั้งสิ้น</value>
        [DataMember(Name="grandTotal", EmitDefaultValue=true)]
        public decimal GrandTotal { get; set; }

        /// <summary>
        /// หมายเหตุ
        /// </summary>
        /// <value>หมายเหตุ</value>
        [DataMember(Name="remarks", EmitDefaultValue=true)]
        public string Remarks { get; set; }

        /// <summary>
        /// โน๊ตภายในบริษัท
        /// </summary>
        /// <value>โน๊ตภายในบริษัท</value>
        [DataMember(Name="internalNotes", EmitDefaultValue=true)]
        public string InternalNotes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExpenseInlineDocument {\n");
            sb.Append("  DocumentSerial: ").Append(DocumentSerial).Append("\n");
            sb.Append("  ContactCode: ").Append(ContactCode).Append("\n");
            sb.Append("  ContactName: ").Append(ContactName).Append("\n");
            sb.Append("  ContactAddress: ").Append(ContactAddress).Append("\n");
            sb.Append("  ContactTaxId: ").Append(ContactTaxId).Append("\n");
            sb.Append("  ContactBranch: ").Append(ContactBranch).Append("\n");
            sb.Append("  ContactPerson: ").Append(ContactPerson).Append("\n");
            sb.Append("  ContactEmail: ").Append(ContactEmail).Append("\n");
            sb.Append("  ContactNumber: ").Append(ContactNumber).Append("\n");
            sb.Append("  ContactZipCode: ").Append(ContactZipCode).Append("\n");
            sb.Append("  PublishedOn: ").Append(PublishedOn).Append("\n");
            sb.Append("  CreditType: ").Append(CreditType).Append("\n");
            sb.Append("  CreditDays: ").Append(CreditDays).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  SalesName: ").Append(SalesName).Append("\n");
            sb.Append("  ProjectName: ").Append(ProjectName).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  IsVatInclusive: ").Append(IsVatInclusive).Append("\n");
            sb.Append("  DiscountType: ").Append(DiscountType).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  SubTotal: ").Append(SubTotal).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  TotalAfterDiscount: ").Append(TotalAfterDiscount).Append("\n");
            sb.Append("  ExemptAmount: ").Append(ExemptAmount).Append("\n");
            sb.Append("  VatableAmount: ").Append(VatableAmount).Append("\n");
            sb.Append("  VatAmount: ").Append(VatAmount).Append("\n");
            sb.Append("  GrandTotal: ").Append(GrandTotal).Append("\n");
            sb.Append("  Remarks: ").Append(Remarks).Append("\n");
            sb.Append("  InternalNotes: ").Append(InternalNotes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExpenseInlineDocument);
        }

        /// <summary>
        /// Returns true if ExpenseInlineDocument instances are equal
        /// </summary>
        /// <param name="input">Instance of ExpenseInlineDocument to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExpenseInlineDocument input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DocumentSerial == input.DocumentSerial ||
                    (this.DocumentSerial != null &&
                    this.DocumentSerial.Equals(input.DocumentSerial))
                ) && 
                (
                    this.ContactCode == input.ContactCode ||
                    (this.ContactCode != null &&
                    this.ContactCode.Equals(input.ContactCode))
                ) && 
                (
                    this.ContactName == input.ContactName ||
                    (this.ContactName != null &&
                    this.ContactName.Equals(input.ContactName))
                ) && 
                (
                    this.ContactAddress == input.ContactAddress ||
                    (this.ContactAddress != null &&
                    this.ContactAddress.Equals(input.ContactAddress))
                ) && 
                (
                    this.ContactTaxId == input.ContactTaxId ||
                    (this.ContactTaxId != null &&
                    this.ContactTaxId.Equals(input.ContactTaxId))
                ) && 
                (
                    this.ContactBranch == input.ContactBranch ||
                    (this.ContactBranch != null &&
                    this.ContactBranch.Equals(input.ContactBranch))
                ) && 
                (
                    this.ContactPerson == input.ContactPerson ||
                    (this.ContactPerson != null &&
                    this.ContactPerson.Equals(input.ContactPerson))
                ) && 
                (
                    this.ContactEmail == input.ContactEmail ||
                    (this.ContactEmail != null &&
                    this.ContactEmail.Equals(input.ContactEmail))
                ) && 
                (
                    this.ContactNumber == input.ContactNumber ||
                    (this.ContactNumber != null &&
                    this.ContactNumber.Equals(input.ContactNumber))
                ) && 
                (
                    this.ContactZipCode == input.ContactZipCode ||
                    (this.ContactZipCode != null &&
                    this.ContactZipCode.Equals(input.ContactZipCode))
                ) && 
                (
                    this.PublishedOn == input.PublishedOn ||
                    (this.PublishedOn != null &&
                    this.PublishedOn.Equals(input.PublishedOn))
                ) && 
                (
                    this.CreditType == input.CreditType ||
                    (this.CreditType != null &&
                    this.CreditType.Equals(input.CreditType))
                ) && 
                (
                    this.CreditDays == input.CreditDays ||
                    (this.CreditDays != null &&
                    this.CreditDays.Equals(input.CreditDays))
                ) && 
                (
                    this.DueDate == input.DueDate ||
                    (this.DueDate != null &&
                    this.DueDate.Equals(input.DueDate))
                ) && 
                (
                    this.SalesName == input.SalesName ||
                    (this.SalesName != null &&
                    this.SalesName.Equals(input.SalesName))
                ) && 
                (
                    this.ProjectName == input.ProjectName ||
                    (this.ProjectName != null &&
                    this.ProjectName.Equals(input.ProjectName))
                ) && 
                (
                    this.Reference == input.Reference ||
                    (this.Reference != null &&
                    this.Reference.Equals(input.Reference))
                ) && 
                (
                    this.IsVatInclusive == input.IsVatInclusive ||
                    (this.IsVatInclusive != null &&
                    this.IsVatInclusive.Equals(input.IsVatInclusive))
                ) && 
                (
                    this.DiscountType == input.DiscountType ||
                    (this.DiscountType != null &&
                    this.DiscountType.Equals(input.DiscountType))
                ) && 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                ) && 
                (
                    this.SubTotal == input.SubTotal ||
                    (this.SubTotal != null &&
                    this.SubTotal.Equals(input.SubTotal))
                ) && 
                (
                    this.DiscountAmount == input.DiscountAmount ||
                    (this.DiscountAmount != null &&
                    this.DiscountAmount.Equals(input.DiscountAmount))
                ) && 
                (
                    this.TotalAfterDiscount == input.TotalAfterDiscount ||
                    (this.TotalAfterDiscount != null &&
                    this.TotalAfterDiscount.Equals(input.TotalAfterDiscount))
                ) && 
                (
                    this.ExemptAmount == input.ExemptAmount ||
                    (this.ExemptAmount != null &&
                    this.ExemptAmount.Equals(input.ExemptAmount))
                ) && 
                (
                    this.VatableAmount == input.VatableAmount ||
                    (this.VatableAmount != null &&
                    this.VatableAmount.Equals(input.VatableAmount))
                ) && 
                (
                    this.VatAmount == input.VatAmount ||
                    (this.VatAmount != null &&
                    this.VatAmount.Equals(input.VatAmount))
                ) && 
                (
                    this.GrandTotal == input.GrandTotal ||
                    (this.GrandTotal != null &&
                    this.GrandTotal.Equals(input.GrandTotal))
                ) && 
                (
                    this.Remarks == input.Remarks ||
                    (this.Remarks != null &&
                    this.Remarks.Equals(input.Remarks))
                ) && 
                (
                    this.InternalNotes == input.InternalNotes ||
                    (this.InternalNotes != null &&
                    this.InternalNotes.Equals(input.InternalNotes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DocumentSerial != null)
                    hashCode = hashCode * 59 + this.DocumentSerial.GetHashCode();
                if (this.ContactCode != null)
                    hashCode = hashCode * 59 + this.ContactCode.GetHashCode();
                if (this.ContactName != null)
                    hashCode = hashCode * 59 + this.ContactName.GetHashCode();
                if (this.ContactAddress != null)
                    hashCode = hashCode * 59 + this.ContactAddress.GetHashCode();
                if (this.ContactTaxId != null)
                    hashCode = hashCode * 59 + this.ContactTaxId.GetHashCode();
                if (this.ContactBranch != null)
                    hashCode = hashCode * 59 + this.ContactBranch.GetHashCode();
                if (this.ContactPerson != null)
                    hashCode = hashCode * 59 + this.ContactPerson.GetHashCode();
                if (this.ContactEmail != null)
                    hashCode = hashCode * 59 + this.ContactEmail.GetHashCode();
                if (this.ContactNumber != null)
                    hashCode = hashCode * 59 + this.ContactNumber.GetHashCode();
                if (this.ContactZipCode != null)
                    hashCode = hashCode * 59 + this.ContactZipCode.GetHashCode();
                if (this.PublishedOn != null)
                    hashCode = hashCode * 59 + this.PublishedOn.GetHashCode();
                if (this.CreditType != null)
                    hashCode = hashCode * 59 + this.CreditType.GetHashCode();
                if (this.CreditDays != null)
                    hashCode = hashCode * 59 + this.CreditDays.GetHashCode();
                if (this.DueDate != null)
                    hashCode = hashCode * 59 + this.DueDate.GetHashCode();
                if (this.SalesName != null)
                    hashCode = hashCode * 59 + this.SalesName.GetHashCode();
                if (this.ProjectName != null)
                    hashCode = hashCode * 59 + this.ProjectName.GetHashCode();
                if (this.Reference != null)
                    hashCode = hashCode * 59 + this.Reference.GetHashCode();
                if (this.IsVatInclusive != null)
                    hashCode = hashCode * 59 + this.IsVatInclusive.GetHashCode();
                if (this.DiscountType != null)
                    hashCode = hashCode * 59 + this.DiscountType.GetHashCode();
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                if (this.SubTotal != null)
                    hashCode = hashCode * 59 + this.SubTotal.GetHashCode();
                if (this.DiscountAmount != null)
                    hashCode = hashCode * 59 + this.DiscountAmount.GetHashCode();
                if (this.TotalAfterDiscount != null)
                    hashCode = hashCode * 59 + this.TotalAfterDiscount.GetHashCode();
                if (this.ExemptAmount != null)
                    hashCode = hashCode * 59 + this.ExemptAmount.GetHashCode();
                if (this.VatableAmount != null)
                    hashCode = hashCode * 59 + this.VatableAmount.GetHashCode();
                if (this.VatAmount != null)
                    hashCode = hashCode * 59 + this.VatAmount.GetHashCode();
                if (this.GrandTotal != null)
                    hashCode = hashCode * 59 + this.GrandTotal.GetHashCode();
                if (this.Remarks != null)
                    hashCode = hashCode * 59 + this.Remarks.GetHashCode();
                if (this.InternalNotes != null)
                    hashCode = hashCode * 59 + this.InternalNotes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
