/* 
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Flowaccount.OpenAPITools.Client.OpenAPIDateConverter;

namespace Flowaccount.OpenAPITools.Model
{
    /// <summary>
    /// ExpenseSimpleProductItem
    /// </summary>
    [DataContract]
    public partial class ExpenseSimpleProductItem :  IEquatable<ExpenseSimpleProductItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExpenseSimpleProductItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExpenseSimpleProductItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExpenseSimpleProductItem" /> class.
        /// </summary>
        /// <param name="description">description expense (required).</param>
        /// <param name="systemCode">system code (required).</param>
        /// <param name="categoryId">id of expense category (required).</param>
        /// <param name="nameForeign">name foreign of expense category (required).</param>
        /// <param name="nameLocal">name local of expense category (required).</param>
        /// <param name="creditCategory">credit category (required).</param>
        /// <param name="creditId">id of expense credit (required).</param>
        /// <param name="creditCode">code of expense credit category (required).</param>
        /// <param name="creditNameForeign">name foreign of expense credit category (required).</param>
        /// <param name="creditNameLocal">name local of expense credit category (required).</param>
        /// <param name="debitCategory">debit category (required).</param>
        /// <param name="debitId">id of expense debit (required).</param>
        /// <param name="debitCode">code of expense debit category (required).</param>
        /// <param name="debitNameForeign">name foreign of expense debit category (required).</param>
        /// <param name="debitNameLocal">name local of expense debit category (required).</param>
        /// <param name="quantity">จำนวนรายการ (required).</param>
        /// <param name="unitName">หน่วยรายการ.</param>
        /// <param name="pricePerUnit">มูลค่าค่าใช้จ่าย (required).</param>
        /// <param name="total">มูลค่ารวม (required).</param>
        public ExpenseSimpleProductItem(string description = default(string), int systemCode = default(int), int categoryId = default(int), string nameForeign = default(string), string nameLocal = default(string), int creditCategory = default(int), int creditId = default(int), string creditCode = default(string), string creditNameForeign = default(string), string creditNameLocal = default(string), int debitCategory = default(int), int debitId = default(int), string debitCode = default(string), string debitNameForeign = default(string), string debitNameLocal = default(string), decimal quantity = default(decimal), string unitName = default(string), decimal pricePerUnit = default(decimal), decimal total = default(decimal))
        {
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            
            // to ensure "systemCode" is required (not null)
            if (systemCode == null)
            {
                throw new InvalidDataException("systemCode is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.SystemCode = systemCode;
            }
            
            // to ensure "categoryId" is required (not null)
            if (categoryId == null)
            {
                throw new InvalidDataException("categoryId is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.CategoryId = categoryId;
            }
            
            // to ensure "nameForeign" is required (not null)
            if (nameForeign == null)
            {
                throw new InvalidDataException("nameForeign is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.NameForeign = nameForeign;
            }
            
            // to ensure "nameLocal" is required (not null)
            if (nameLocal == null)
            {
                throw new InvalidDataException("nameLocal is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.NameLocal = nameLocal;
            }
            
            // to ensure "creditCategory" is required (not null)
            if (creditCategory == null)
            {
                throw new InvalidDataException("creditCategory is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.CreditCategory = creditCategory;
            }
            
            // to ensure "creditId" is required (not null)
            if (creditId == null)
            {
                throw new InvalidDataException("creditId is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.CreditId = creditId;
            }
            
            // to ensure "creditCode" is required (not null)
            if (creditCode == null)
            {
                throw new InvalidDataException("creditCode is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.CreditCode = creditCode;
            }
            
            // to ensure "creditNameForeign" is required (not null)
            if (creditNameForeign == null)
            {
                throw new InvalidDataException("creditNameForeign is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.CreditNameForeign = creditNameForeign;
            }
            
            // to ensure "creditNameLocal" is required (not null)
            if (creditNameLocal == null)
            {
                throw new InvalidDataException("creditNameLocal is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.CreditNameLocal = creditNameLocal;
            }
            
            // to ensure "debitCategory" is required (not null)
            if (debitCategory == null)
            {
                throw new InvalidDataException("debitCategory is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.DebitCategory = debitCategory;
            }
            
            // to ensure "debitId" is required (not null)
            if (debitId == null)
            {
                throw new InvalidDataException("debitId is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.DebitId = debitId;
            }
            
            // to ensure "debitCode" is required (not null)
            if (debitCode == null)
            {
                throw new InvalidDataException("debitCode is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.DebitCode = debitCode;
            }
            
            // to ensure "debitNameForeign" is required (not null)
            if (debitNameForeign == null)
            {
                throw new InvalidDataException("debitNameForeign is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.DebitNameForeign = debitNameForeign;
            }
            
            // to ensure "debitNameLocal" is required (not null)
            if (debitNameLocal == null)
            {
                throw new InvalidDataException("debitNameLocal is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.DebitNameLocal = debitNameLocal;
            }
            
            // to ensure "quantity" is required (not null)
            if (quantity == null)
            {
                throw new InvalidDataException("quantity is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.Quantity = quantity;
            }
            
            // to ensure "pricePerUnit" is required (not null)
            if (pricePerUnit == null)
            {
                throw new InvalidDataException("pricePerUnit is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.PricePerUnit = pricePerUnit;
            }
            
            // to ensure "total" is required (not null)
            if (total == null)
            {
                throw new InvalidDataException("total is a required property for ExpenseSimpleProductItem and cannot be null");
            }
            else
            {
                this.Total = total;
            }
            
            this.UnitName = unitName;
        }
        
        /// <summary>
        /// description expense
        /// </summary>
        /// <value>description expense</value>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// system code
        /// </summary>
        /// <value>system code</value>
        [DataMember(Name="systemCode", EmitDefaultValue=true)]
        public int SystemCode { get; set; }

        /// <summary>
        /// id of expense category
        /// </summary>
        /// <value>id of expense category</value>
        [DataMember(Name="categoryId", EmitDefaultValue=true)]
        public int CategoryId { get; set; }

        /// <summary>
        /// name foreign of expense category
        /// </summary>
        /// <value>name foreign of expense category</value>
        [DataMember(Name="nameForeign", EmitDefaultValue=true)]
        public string NameForeign { get; set; }

        /// <summary>
        /// name local of expense category
        /// </summary>
        /// <value>name local of expense category</value>
        [DataMember(Name="nameLocal", EmitDefaultValue=true)]
        public string NameLocal { get; set; }

        /// <summary>
        /// credit category
        /// </summary>
        /// <value>credit category</value>
        [DataMember(Name="creditCategory", EmitDefaultValue=true)]
        public int CreditCategory { get; set; }

        /// <summary>
        /// id of expense credit
        /// </summary>
        /// <value>id of expense credit</value>
        [DataMember(Name="creditId", EmitDefaultValue=true)]
        public int CreditId { get; set; }

        /// <summary>
        /// code of expense credit category
        /// </summary>
        /// <value>code of expense credit category</value>
        [DataMember(Name="creditCode", EmitDefaultValue=true)]
        public string CreditCode { get; set; }

        /// <summary>
        /// name foreign of expense credit category
        /// </summary>
        /// <value>name foreign of expense credit category</value>
        [DataMember(Name="creditNameForeign", EmitDefaultValue=true)]
        public string CreditNameForeign { get; set; }

        /// <summary>
        /// name local of expense credit category
        /// </summary>
        /// <value>name local of expense credit category</value>
        [DataMember(Name="creditNameLocal", EmitDefaultValue=true)]
        public string CreditNameLocal { get; set; }

        /// <summary>
        /// debit category
        /// </summary>
        /// <value>debit category</value>
        [DataMember(Name="debitCategory", EmitDefaultValue=true)]
        public int DebitCategory { get; set; }

        /// <summary>
        /// id of expense debit
        /// </summary>
        /// <value>id of expense debit</value>
        [DataMember(Name="debitId", EmitDefaultValue=true)]
        public int DebitId { get; set; }

        /// <summary>
        /// code of expense debit category
        /// </summary>
        /// <value>code of expense debit category</value>
        [DataMember(Name="debitCode", EmitDefaultValue=true)]
        public string DebitCode { get; set; }

        /// <summary>
        /// name foreign of expense debit category
        /// </summary>
        /// <value>name foreign of expense debit category</value>
        [DataMember(Name="debitNameForeign", EmitDefaultValue=true)]
        public string DebitNameForeign { get; set; }

        /// <summary>
        /// name local of expense debit category
        /// </summary>
        /// <value>name local of expense debit category</value>
        [DataMember(Name="debitNameLocal", EmitDefaultValue=true)]
        public string DebitNameLocal { get; set; }

        /// <summary>
        /// จำนวนรายการ
        /// </summary>
        /// <value>จำนวนรายการ</value>
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public decimal Quantity { get; set; }

        /// <summary>
        /// หน่วยรายการ
        /// </summary>
        /// <value>หน่วยรายการ</value>
        [DataMember(Name="unitName", EmitDefaultValue=true)]
        public string UnitName { get; set; }

        /// <summary>
        /// มูลค่าค่าใช้จ่าย
        /// </summary>
        /// <value>มูลค่าค่าใช้จ่าย</value>
        [DataMember(Name="pricePerUnit", EmitDefaultValue=true)]
        public decimal PricePerUnit { get; set; }

        /// <summary>
        /// มูลค่ารวม
        /// </summary>
        /// <value>มูลค่ารวม</value>
        [DataMember(Name="total", EmitDefaultValue=true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExpenseSimpleProductItem {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  SystemCode: ").Append(SystemCode).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  NameForeign: ").Append(NameForeign).Append("\n");
            sb.Append("  NameLocal: ").Append(NameLocal).Append("\n");
            sb.Append("  CreditCategory: ").Append(CreditCategory).Append("\n");
            sb.Append("  CreditId: ").Append(CreditId).Append("\n");
            sb.Append("  CreditCode: ").Append(CreditCode).Append("\n");
            sb.Append("  CreditNameForeign: ").Append(CreditNameForeign).Append("\n");
            sb.Append("  CreditNameLocal: ").Append(CreditNameLocal).Append("\n");
            sb.Append("  DebitCategory: ").Append(DebitCategory).Append("\n");
            sb.Append("  DebitId: ").Append(DebitId).Append("\n");
            sb.Append("  DebitCode: ").Append(DebitCode).Append("\n");
            sb.Append("  DebitNameForeign: ").Append(DebitNameForeign).Append("\n");
            sb.Append("  DebitNameLocal: ").Append(DebitNameLocal).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitName: ").Append(UnitName).Append("\n");
            sb.Append("  PricePerUnit: ").Append(PricePerUnit).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExpenseSimpleProductItem);
        }

        /// <summary>
        /// Returns true if ExpenseSimpleProductItem instances are equal
        /// </summary>
        /// <param name="input">Instance of ExpenseSimpleProductItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExpenseSimpleProductItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.SystemCode == input.SystemCode ||
                    (this.SystemCode != null &&
                    this.SystemCode.Equals(input.SystemCode))
                ) && 
                (
                    this.CategoryId == input.CategoryId ||
                    (this.CategoryId != null &&
                    this.CategoryId.Equals(input.CategoryId))
                ) && 
                (
                    this.NameForeign == input.NameForeign ||
                    (this.NameForeign != null &&
                    this.NameForeign.Equals(input.NameForeign))
                ) && 
                (
                    this.NameLocal == input.NameLocal ||
                    (this.NameLocal != null &&
                    this.NameLocal.Equals(input.NameLocal))
                ) && 
                (
                    this.CreditCategory == input.CreditCategory ||
                    (this.CreditCategory != null &&
                    this.CreditCategory.Equals(input.CreditCategory))
                ) && 
                (
                    this.CreditId == input.CreditId ||
                    (this.CreditId != null &&
                    this.CreditId.Equals(input.CreditId))
                ) && 
                (
                    this.CreditCode == input.CreditCode ||
                    (this.CreditCode != null &&
                    this.CreditCode.Equals(input.CreditCode))
                ) && 
                (
                    this.CreditNameForeign == input.CreditNameForeign ||
                    (this.CreditNameForeign != null &&
                    this.CreditNameForeign.Equals(input.CreditNameForeign))
                ) && 
                (
                    this.CreditNameLocal == input.CreditNameLocal ||
                    (this.CreditNameLocal != null &&
                    this.CreditNameLocal.Equals(input.CreditNameLocal))
                ) && 
                (
                    this.DebitCategory == input.DebitCategory ||
                    (this.DebitCategory != null &&
                    this.DebitCategory.Equals(input.DebitCategory))
                ) && 
                (
                    this.DebitId == input.DebitId ||
                    (this.DebitId != null &&
                    this.DebitId.Equals(input.DebitId))
                ) && 
                (
                    this.DebitCode == input.DebitCode ||
                    (this.DebitCode != null &&
                    this.DebitCode.Equals(input.DebitCode))
                ) && 
                (
                    this.DebitNameForeign == input.DebitNameForeign ||
                    (this.DebitNameForeign != null &&
                    this.DebitNameForeign.Equals(input.DebitNameForeign))
                ) && 
                (
                    this.DebitNameLocal == input.DebitNameLocal ||
                    (this.DebitNameLocal != null &&
                    this.DebitNameLocal.Equals(input.DebitNameLocal))
                ) && 
                (
                    this.Quantity == input.Quantity ||
                    (this.Quantity != null &&
                    this.Quantity.Equals(input.Quantity))
                ) && 
                (
                    this.UnitName == input.UnitName ||
                    (this.UnitName != null &&
                    this.UnitName.Equals(input.UnitName))
                ) && 
                (
                    this.PricePerUnit == input.PricePerUnit ||
                    (this.PricePerUnit != null &&
                    this.PricePerUnit.Equals(input.PricePerUnit))
                ) && 
                (
                    this.Total == input.Total ||
                    (this.Total != null &&
                    this.Total.Equals(input.Total))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.SystemCode != null)
                    hashCode = hashCode * 59 + this.SystemCode.GetHashCode();
                if (this.CategoryId != null)
                    hashCode = hashCode * 59 + this.CategoryId.GetHashCode();
                if (this.NameForeign != null)
                    hashCode = hashCode * 59 + this.NameForeign.GetHashCode();
                if (this.NameLocal != null)
                    hashCode = hashCode * 59 + this.NameLocal.GetHashCode();
                if (this.CreditCategory != null)
                    hashCode = hashCode * 59 + this.CreditCategory.GetHashCode();
                if (this.CreditId != null)
                    hashCode = hashCode * 59 + this.CreditId.GetHashCode();
                if (this.CreditCode != null)
                    hashCode = hashCode * 59 + this.CreditCode.GetHashCode();
                if (this.CreditNameForeign != null)
                    hashCode = hashCode * 59 + this.CreditNameForeign.GetHashCode();
                if (this.CreditNameLocal != null)
                    hashCode = hashCode * 59 + this.CreditNameLocal.GetHashCode();
                if (this.DebitCategory != null)
                    hashCode = hashCode * 59 + this.DebitCategory.GetHashCode();
                if (this.DebitId != null)
                    hashCode = hashCode * 59 + this.DebitId.GetHashCode();
                if (this.DebitCode != null)
                    hashCode = hashCode * 59 + this.DebitCode.GetHashCode();
                if (this.DebitNameForeign != null)
                    hashCode = hashCode * 59 + this.DebitNameForeign.GetHashCode();
                if (this.DebitNameLocal != null)
                    hashCode = hashCode * 59 + this.DebitNameLocal.GetHashCode();
                if (this.Quantity != null)
                    hashCode = hashCode * 59 + this.Quantity.GetHashCode();
                if (this.UnitName != null)
                    hashCode = hashCode * 59 + this.UnitName.GetHashCode();
                if (this.PricePerUnit != null)
                    hashCode = hashCode * 59 + this.PricePerUnit.GetHashCode();
                if (this.Total != null)
                    hashCode = hashCode * 59 + this.Total.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // UnitName (string) maxLength
            if(this.UnitName != null && this.UnitName.Length > 7)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UnitName, length must be less than 7.", new [] { "UnitName" });
            }

            yield break;
        }
    }

}
