/* 
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Flowaccount.OpenAPITools.Client.OpenAPIDateConverter;

namespace Flowaccount.OpenAPITools.Model
{
    /// <summary>
    /// SimpleDocumentAllOf
    /// </summary>
    [DataContract]
    public partial class SimpleDocumentAllOf :  IEquatable<SimpleDocumentAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleDocumentAllOf" /> class.
        /// </summary>
        /// <param name="items">items.</param>
        /// <param name="documentReferences">documentReferences.</param>
        public SimpleDocumentAllOf(List<SimpleProductItem> items = default(List<SimpleProductItem>), List<UpgradeDocument> documentReferences = default(List<UpgradeDocument>))
        {
            this.Items = items;
            this.DocumentReferences = documentReferences;
        }
        
        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name="items", EmitDefaultValue=true)]
        public List<SimpleProductItem> Items { get; set; }

        /// <summary>
        /// Gets or Sets DocumentReferences
        /// </summary>
        [DataMember(Name="documentReferences", EmitDefaultValue=true)]
        public List<UpgradeDocument> DocumentReferences { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SimpleDocumentAllOf {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  DocumentReferences: ").Append(DocumentReferences).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SimpleDocumentAllOf);
        }

        /// <summary>
        /// Returns true if SimpleDocumentAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of SimpleDocumentAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SimpleDocumentAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                ) && 
                (
                    this.DocumentReferences == input.DocumentReferences ||
                    this.DocumentReferences != null &&
                    input.DocumentReferences != null &&
                    this.DocumentReferences.SequenceEqual(input.DocumentReferences)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                if (this.DocumentReferences != null)
                    hashCode = hashCode * 59 + this.DocumentReferences.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
