/* 
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineProductItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineProductItemTests
    {
        // TODO uncomment below to declare an instance variable for InlineProductItem
        //private InlineProductItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineProductItem
            //instance = new InlineProductItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineProductItem
        /// </summary>
        [Test]
        public void InlineProductItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineProductItem
            //Assert.IsInstanceOf(typeof(InlineProductItem), instance);
        }


        /// <summary>
        /// Test the property 'DiscountAmountPercentage'
        /// </summary>
        [Test]
        public void DiscountAmountPercentageTest()
        {
            // TODO unit test for the property 'DiscountAmountPercentage'
        }
        /// <summary>
        /// Test the property 'DiscountAmount'
        /// </summary>
        [Test]
        public void DiscountAmountTest()
        {
            // TODO unit test for the property 'DiscountAmount'
        }
        /// <summary>
        /// Test the property 'VatRate'
        /// </summary>
        [Test]
        public void VatRateTest()
        {
            // TODO unit test for the property 'VatRate'
        }

    }

}
