/* 
 * FlowAccount Open API
 *
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PaymentDocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentDocumentResponseTests
    {
        // TODO uncomment below to declare an instance variable for PaymentDocumentResponse
        //private PaymentDocumentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentDocumentResponse
            //instance = new PaymentDocumentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentDocumentResponse
        /// </summary>
        [Test]
        public void PaymentDocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PaymentDocumentResponse
            //Assert.IsInstanceOf(typeof(PaymentDocumentResponse), instance);
        }


        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Test]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'Collected'
        /// </summary>
        [Test]
        public void CollectedTest()
        {
            // TODO unit test for the property 'Collected'
        }
        /// <summary>
        /// Test the property 'PaymentDeductionType'
        /// </summary>
        [Test]
        public void PaymentDeductionTypeTest()
        {
            // TODO unit test for the property 'PaymentDeductionType'
        }
        /// <summary>
        /// Test the property 'DeductionAmount'
        /// </summary>
        [Test]
        public void DeductionAmountTest()
        {
            // TODO unit test for the property 'DeductionAmount'
        }
        /// <summary>
        /// Test the property 'WithheldPercentage'
        /// </summary>
        [Test]
        public void WithheldPercentageTest()
        {
            // TODO unit test for the property 'WithheldPercentage'
        }
        /// <summary>
        /// Test the property 'WithheldAmount'
        /// </summary>
        [Test]
        public void WithheldAmountTest()
        {
            // TODO unit test for the property 'WithheldAmount'
        }
        /// <summary>
        /// Test the property 'Charge'
        /// </summary>
        [Test]
        public void ChargeTest()
        {
            // TODO unit test for the property 'Charge'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PaymentChannel'
        /// </summary>
        [Test]
        public void PaymentChannelTest()
        {
            // TODO unit test for the property 'PaymentChannel'
        }
        /// <summary>
        /// Test the property 'PaymentRemarks'
        /// </summary>
        [Test]
        public void PaymentRemarksTest()
        {
            // TODO unit test for the property 'PaymentRemarks'
        }
        /// <summary>
        /// Test the property 'BankAccountName'
        /// </summary>
        [Test]
        public void BankAccountNameTest()
        {
            // TODO unit test for the property 'BankAccountName'
        }
        /// <summary>
        /// Test the property 'BankAccountNumber'
        /// </summary>
        [Test]
        public void BankAccountNumberTest()
        {
            // TODO unit test for the property 'BankAccountNumber'
        }
        /// <summary>
        /// Test the property 'ChequeDate'
        /// </summary>
        [Test]
        public void ChequeDateTest()
        {
            // TODO unit test for the property 'ChequeDate'
        }
        /// <summary>
        /// Test the property 'ChequeNumber'
        /// </summary>
        [Test]
        public void ChequeNumberTest()
        {
            // TODO unit test for the property 'ChequeNumber'
        }
        /// <summary>
        /// Test the property 'ChequeBankAccountId'
        /// </summary>
        [Test]
        public void ChequeBankAccountIdTest()
        {
            // TODO unit test for the property 'ChequeBankAccountId'
        }
        /// <summary>
        /// Test the property 'CreditCardBankAccountId'
        /// </summary>
        [Test]
        public void CreditCardBankAccountIdTest()
        {
            // TODO unit test for the property 'CreditCardBankAccountId'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Test]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'RemainingCollectedType'
        /// </summary>
        [Test]
        public void RemainingCollectedTypeTest()
        {
            // TODO unit test for the property 'RemainingCollectedType'
        }
        /// <summary>
        /// Test the property 'RemainingCollected'
        /// </summary>
        [Test]
        public void RemainingCollectedTest()
        {
            // TODO unit test for the property 'RemainingCollected'
        }

    }

}
