/* 
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SendEmailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendEmailResponseTests
    {
        // TODO uncomment below to declare an instance variable for SendEmailResponse
        //private SendEmailResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendEmailResponse
            //instance = new SendEmailResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendEmailResponse
        /// </summary>
        [Test]
        public void SendEmailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SendEmailResponse
            //Assert.IsInstanceOf(typeof(SendEmailResponse), instance);
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Ok'
        /// </summary>
        [Test]
        public void OkTest()
        {
            // TODO unit test for the property 'Ok'
        }
        /// <summary>
        /// Test the property 'SuccessMsg'
        /// </summary>
        [Test]
        public void SuccessMsgTest()
        {
            // TODO unit test for the property 'SuccessMsg'
        }

    }

}
