/* 
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2-oas3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusResponseTests
    {
        // TODO uncomment below to declare an instance variable for StatusResponse
        //private StatusResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StatusResponse
            //instance = new StatusResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatusResponse
        /// </summary>
        [Test]
        public void StatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StatusResponse
            //Assert.IsInstanceOf(typeof(StatusResponse), instance);
        }


        /// <summary>
        /// Test the property 'RecordId'
        /// </summary>
        [Test]
        public void RecordIdTest()
        {
            // TODO unit test for the property 'RecordId'
        }
        /// <summary>
        /// Test the property 'ReferencedToMe'
        /// </summary>
        [Test]
        public void ReferencedToMeTest()
        {
            // TODO unit test for the property 'ReferencedToMe'
        }
        /// <summary>
        /// Test the property 'ReferencedByMe'
        /// </summary>
        [Test]
        public void ReferencedByMeTest()
        {
            // TODO unit test for the property 'ReferencedByMe'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusString'
        /// </summary>
        [Test]
        public void StatusStringTest()
        {
            // TODO unit test for the property 'StatusString'
        }
        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Test]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }
        /// <summary>
        /// Test the property 'AllowDelete'
        /// </summary>
        [Test]
        public void AllowDeleteTest()
        {
            // TODO unit test for the property 'AllowDelete'
        }

    }

}
