/* 
 * FlowAccount Open API
 *
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Flowaccount.OpenAPITools.Client;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing WithholdingTaxApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WithholdingTaxApiTests
    {
        private WithholdingTaxApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WithholdingTaxApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WithholdingTaxApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' WithholdingTaxApi
            //Assert.IsInstanceOf(typeof(WithholdingTaxApi), instance);
        }

        
        /// <summary>
        /// Test WithholdingTaxesGet
        /// </summary>
        [Test]
        public void WithholdingTaxesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //var response = instance.WithholdingTaxesGet(authorization);
            //Assert.IsInstanceOf(typeof(WithholidingTaxDocumentResponse), response, "response is WithholidingTaxDocumentResponse");
        }
        
        /// <summary>
        /// Test WithholdingTaxesIdGet
        /// </summary>
        [Test]
        public void WithholdingTaxesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string id = null;
            //var response = instance.WithholdingTaxesIdGet(authorization, id);
            //Assert.IsInstanceOf(typeof(WithholidingTaxDocumentResponse), response, "response is WithholidingTaxDocumentResponse");
        }
        
        /// <summary>
        /// Test WithholdingTaxesPost
        /// </summary>
        [Test]
        public void WithholdingTaxesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //WithholidingTaxDocument withholidingTaxDocument = null;
            //var response = instance.WithholdingTaxesPost(authorization, withholidingTaxDocument);
            //Assert.IsInstanceOf(typeof(WithholidingTaxDocumentResponse), response, "response is WithholidingTaxDocumentResponse");
        }
        
    }

}
